return {
  "junegunn/fzf.vim",
  dependencies = {
    "junegunn/fzf",
  },
  cmd = {
    "Files",
    "GFiles",
    "Buffers",
    "Colors",
    "Ag",
    "Rg",
    "RG",
    "Lines",
    "BLines",
    "Tags",
    "BTags",
    "Changes",
    "Marks",
    "Jumps",
    "Windows",
    "Locate",
    "History",
    "Snippets",
    "Commits",
    "BCommits",
    "Commands",
    "Maps",
    "Helptags",
    "Filetypes",
  },
  keys = {
    { "<leader>of", "<Cmd>Files<CR>", desc = "Files" },
    { "<leader>oc", "<Cmd>Commands<CR>", desc = "Commands" },
  },
}
