return {
  "rktjmp/lush.nvim",
  "catppuccin/nvim",
  "folke/tokyonight.nvim",
  "aktersnurra/no-clown-fiesta.nvim",
  "nyoom-engineering/oxocarbon.nvim",
  "mcchrish/zenbones.nvim",
  "nvim-tree/nvim-web-devicons",
  "EdenEast/nightfox.nvim",
  "nyoom-engineering/oxocarbon.nvim",
  { "andreasvc/vim-256noir", name = "vim-256noir", lazy = false },
  { "ajgrf/parchment", name = "parchment", lazy = false },
  { "widatama/vim-phoenix", name = "vim-phoenix", lazy = false },
  { "bluz71/vim-moonfly-colors", name = "moonfly", lazy = false, priority = 1000 },
  { "bluz71/vim-nightfly-colors", name = "nightfly", lazy = false, priority = 1000 },
}
